# Generated by Django 5.1.2 on 2025-06-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_trainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdata',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
