# Generated by Django 5.1.2 on 2025-06-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_connectedpage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedpage',
            name='business',
        ),
    ]
