# Generated by Django 5.1.2 on 2025-08-17 08:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_connectedpage_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('fb_page_access_token', models.TextField(help_text='Page Access Token')),
                ('fb_verify_token', models.CharField(help_text='Webhook verify token (Meta will call this)', max_length=255)),
                ('fb_app_secret', models.CharField(help_text='For X-Hub-Signature-256 validation', max_length=255)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=64)),
                ('temperature', models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.PositiveIntegerField(default=300)),
                ('system_prompt', models.TextField(help_text='Brand voice / core instructions')),
                ('business_context', models.TextField(blank=True, help_text='Hours, contacts, etc')),
                ('quick_replies', models.JSONField(blank=True, default=list)),
                ('blocked_keywords', models.JSONField(blank=True, default=list)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='business',
        ),
        migrations.RemoveField(
            model_name='faqentry',
            name='business',
        ),
        migrations.RemoveField(
            model_name='connectedpage',
            name='user',
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='e.g., rates, location, reservation_policy')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='myApp.business')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('business', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='BotSettings',
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
        migrations.DeleteModel(
            name='FAQEntry',
        ),
        migrations.DeleteModel(
            name='ConnectedPage',
        ),
    ]
