# Generated by Django 5.1.2 on 2025-06-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_trainingdata_is_processed_trainingdata_processed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdata',
            name='processed_at',
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='file',
            field=models.FileField(upload_to='training_files/'),
        ),
    ]
