# Generated by Django 5.1.2 on 2025-08-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_business_remove_businessprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='availability_config',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific config (e.g. calendar IDs, API creds)'),
        ),
        migrations.AddField(
            model_name='business',
            name='availability_provider',
            field=models.CharField(choices=[('internal_calendar', 'Internal Calendar'), ('google_calendar', 'Google Calendar')], default='internal_calendar', help_text='Which availability backend to use for this business', max_length=40),
        ),
        migrations.AddField(
            model_name='business',
            name='manage_token',
            field=models.CharField(blank=True, default='', help_text='Optional shared secret for simple API management endpoints', max_length=64),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='How many parallel bookings per slot')),
                ('is_active', models.BooleanField(default=True)),
                ('external_resource_id', models.CharField(blank=True, help_text='Optional mapping to external calendar', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='myApp.business')),
            ],
            options={
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], help_text='0=Mon … 6=Sun')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveIntegerField(default=60)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_rules', to='myApp.business')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_rules', to='myApp.resource')),
            ],
            options={
                'ordering': ['resource', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SlotOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=12)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_overrides', to='myApp.business')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_overrides', to='myApp.resource')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_overrides', to='myApp.business')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_overrides', to='myApp.resource')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('resource', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='hold', max_length=10)),
                ('fb_sender_id', models.CharField(blank=True, help_text='Optional: Messenger user id for follow-up', max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myApp.business')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='myApp.resource')),
            ],
            options={
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['business', 'resource', 'start', 'end', 'status'], name='myApp_booki_busines_0b76cb_idx')],
            },
        ),
    ]
