# Generated by Django 5.1.2 on 2025-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_trainingdata_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdata',
            name='summary_prompt',
            field=models.TextField(blank=True),
        ),
    ]
