# Generated by Django 5.1.2 on 2025-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_businessmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='booking_schema',
            field=models.JSONField(blank=True, default=list, help_text="List of required fields: e.g. ['date', 'time', 'service_type', 'stylist']"),
        ),
    ]
