# Generated by Django 5.1.2 on 2025-08-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_business_booking_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Turn AI router on/off for this business'),
        ),
    ]
