# Generated by Django 5.1.2 on 2025-08-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_business_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='messenger_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for Messenger replies'),
        ),
        migrations.AlterField(
            model_name='business',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for AI routing/replies'),
        ),
    ]
